### ISSUE TITLE
Group last active is overly aggressively triggered

### ISSUE THREAD

**Issue by lordmatt** [cuny-academic-commons/external-group-blogs#12]
I've been noticing that groups last active will update if there is an external blog feed even if there is no new content.

**Comment by lordmatt** [comment]
It looks like groups_update_groupmeta( $group_id, 'last_activity', bp_core_current_time() ); should be inside the if statements one of which looks - from comments - as if it is redundant as we test for empty twice.

**Comment by boonebgorges** [comment]
last_activity is updated here: https://github.com/cuny-academic-commons/external-group-blogs/blob/1.6.x/includes/bp-groups-externalblogs.php#L340

Earlier in the same method, there's a `return` statement if the list of items is empty: https://github.com/cuny-academic-commons/external-group-blogs/blob/1.6.x/includes/bp-groups-externalblogs.php#L270 In theory, this should prevent last_activity from being updated if there are no new posts.

What's probably happening is https://github.com/cuny-academic-commons/external-group-blogs/blob/1.6.x/includes/bp-groups-externalblogs.php#L319 - items are being skipped because they're already in the stream. I'll post a fix.

**Comment by boonebgorges** [comment]
See 0fc8be6
