### ISSUE TITLE
Unexpected behaviour on removing a feed

### ISSUE THREAD

**Issue by lordmatt** [cuny-academic-commons/external-group-blogs#13]
When debugging a problem I removed one of the external feed URLs. This triggered a complete loss of all feed items for the feed. Replacing the feed URL did not restore the feed items.

What I expected was that EGB would just search the new URL only.

**Comment by boonebgorges** [comment]
I can confirm that this is the behavior: https://github.com/cuny-academic-commons/external-group-blogs/blob/1.6.x/includes/bp-groups-externalblogs.php#L151

I believe this was the behavior of the original plugin, from which this one was forked about 10 years ago.

I agree that the behavior is not ideal. It's also not ideal to simply reverse the behavior, by not deleting anything from removed feeds. In an ideal world, there'd be a separate system that would let you delete all items from a given feed, whether or not you're currently subscribed to that feed. However, we haven't got the resources for such a tool. So I think the best course of action is to change the plugin so that it no longer deletes anything. This way, if someone wants to delete a feed but keep the items, then they're all set; if someone wants to delete a feed *and* the old items, they'll have to manually delete each one. This is a minor annoyance.

I think I'll also add a filter so that developers can control this behavior.
